In [39]:
from idlelib.debugobj import dispatch

import pandas as pd
import numpy as np

In [40]:

df1 = pd.DataFrame(
    {'Favorite Food': ['Alfredo Pasta', "Bobba", 'Croissants', "danish Rolls", 'Edamame', 'Fish', "Ice Cream"]},
    index=pd.Index(['Alfred', 'Bob', 'Cris', 'Daniel', 'Edward', 'Fitx', 'Ivan'], name='Name'))
df2 = pd.DataFrame(
    {'Favorite Country': ['Albania', 'Croatia', 'Denmark', 'Fiji', 'Germany', 'Haiti']},
    index=pd.Index(['Alfred', 'Cris', 'Daniel', 'Edward', 'Fitx', 'Ivan'], name='Name'))


display(df1.join(df2, how= 'outer'))  # 합집합
display(df1.join(df2, how= 'inner')) #교집합

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   danish Rolls          Denmark
Edward        Edamame             Fiji
Fitx             Fish          Germany
Ivan        Ice Cream            Haiti

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Cris       Croissants          Croatia
Daniel   danish Rolls          Denmark
Edward        Edamame             Fiji
Fitx             Fish          Germany
Ivan        Ice Cream            Haiti

In [41]:
display(df1.join(df2))

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Bob             Bobba              NaN
Cris       Croissants          Croatia
Daniel   danish Rolls          Denmark
Edward        Edamame             Fiji
Fitx             Fish          Germany
Ivan        Ice Cream            Haiti

In [42]:
display(df1.join(df2, how= 'right'))

        Favorite Food Favorite Country
Name
Alfred  Alfredo Pasta          Albania
Cris       Croissants          Croatia
Daniel   danish Rolls          Denmark
Edward        Edamame             Fiji
Fitx             Fish          Germany
Ivan        Ice Cream            Haiti

In [43]:
# pd.DataFreame : merge (join 보다 더 똑똑한 개념 = merge)
df1 = df1.reset_index()
display(df1)
df2 = df2.reset_index()
display(df2)

# 교집합이 'inner'가  default 값 'how' = 'outer', 'left', 'right' 선택 가능
display(pd.merge(df1,df2))
display(df1.merge(df2))

#
df3 = pd.DataFrame({'Favorite Course':["Criminomogy", "Design", "Fitness"],
                    'Favorite Country':['Croatia','Denmark','Fiji']})
display(df3)
display(pd.merge(df2, df3, left_on='Favorite Country', right_on='Favorite Country'))

     Name  Favorite Food
0  Alfred  Alfredo Pasta
1     Bob          Bobba
2    Cris     Croissants
3  Daniel   danish Rolls
4  Edward        Edamame
5    Fitx           Fish
6    Ivan      Ice Cream

     Name Favorite Country
0  Alfred          Albania
1    Cris          Croatia
2  Daniel          Denmark
3  Edward             Fiji
4    Fitx          Germany
5    Ivan            Haiti

     Name  Favorite Food Favorite Country
0  Alfred  Alfredo Pasta          Albania
1    Cris     Croissants          Croatia
2  Daniel   danish Rolls          Denmark
3  Edward        Edamame             Fiji
4    Fitx           Fish          Germany
5    Ivan      Ice Cream            Haiti

     Name  Favorite Food Favorite Country
0  Alfred  Alfredo Pasta          Albania
1    Cris     Croissants          Croatia
2  Daniel   danish Rolls          Denmark
3  Edward        Edamame             Fiji
4    Fitx           Fish          Germany
5    Ivan      Ice Cream            Haiti

  Favorite Course Favorite Country
0     Criminomogy          Croatia
1          Design          Denmark
2         Fitness             Fiji

     Name Favorite Country Favorite Course
0    Cris          Croatia     Criminomogy
1  Daniel          Denmark          Design
2  Edward             Fiji         Fitness

In [44]:
df4 = pd.DataFrame({'Name':['Cris', 'Daniel','Fitz','Peter'],
                    'Favorite Course':["Criminomogy", "Design", "Fitness",'Yoga'],
                    'Favorite Country':['Croatia','Denmark','Fiji','Croatia'],
                    'Favorite Food':['Croissants','Danish Rolls', 'Fish', 'Meat']})
display(df4)
display(df2)

df2.merge(df4, on = ['Favorite Country'])

     Name Favorite Course Favorite Country Favorite Food
0    Cris     Criminomogy          Croatia    Croissants
1  Daniel          Design          Denmark  Danish Rolls
2    Fitz         Fitness             Fiji          Fish
3   Peter            Yoga          Croatia          Meat

     Name Favorite Country
0  Alfred          Albania
1    Cris          Croatia
2  Daniel          Denmark
3  Edward             Fiji
4    Fitx          Germany
5    Ivan            Haiti

   Name_x Favorite Country  Name_y Favorite Course Favorite Food
0    Cris          Croatia    Cris     Criminomogy    Croissants
1    Cris          Croatia   Peter            Yoga          Meat
2  Daniel          Denmark  Daniel          Design  Danish Rolls
3  Edward             Fiji    Fitz         Fitness          Fish

In [45]:
df = pd.DataFrame({'foo':['one','one','one','two','two','two'],
                   'bar':['A','B','C','A','B','C'],
                   'baz':[1,2,3,4,5,6],
                   'zoo':['x','y','z','q','w','t']})
display(df)
display(df.pivot(index='foo', columns='bar', values='baz'))

df3 = pd.DataFrame({'first':['John', 'Mary'],
                    'last':['Doe', 'Bo'],
                    'height':[5.5, 6.0],
                    'weight':[130,150]})
display(df3)
display(df3.melt(id_vars=['first', 'last']))

   foo bar  baz zoo
0  one   A    1   x
1  one   B    2   y
2  one   C    3   z
3  two   A    4   q
4  two   B    5   w
5  two   C    6   t

bar  A  B  C
foo
one  1  2  3
two  4  5  6

  first last  height  weight
0  John  Doe     5.5     130
1  Mary   Bo     6.0     150

  first last variable  value
0  John  Doe   height    5.5
1  Mary   Bo   height    6.0
2  John  Doe   weight  130.0
3  Mary   Bo   weight  150.0

In [47]:
index = pd.MultiIndex.from_tuples([('bar','one'),('bar','two'),
                                   ('baz','one'),('baz','Two')],
                                  name = ['first', 'second'])
df2 = pd.DataFrame([[1,2],[3,4],[5,6],[7,8]], index=index, columns=['A','B'])
display(df2)

stacked = df2.stack()
display(stacked)
print("-"*10)
print(stacked.index.names) # fist, second, none output
print("-"*10)

display(stacked.unstack())

print(stacked.unstack().index.names)
display(stacked.unstack(1)) # or stacked.unstack('second')
display(stacked.unstack(2)) # or stacked.unstack('first')

              A  B
first second
bar   one     1  2
      two     3  4
baz   one     5  6
      Two     7  8

first  second
bar    one     A    1
               B    2
       two     A    3
               B    4
baz    one     A    5
               B    6
       Two     A    7
               B    8
dtype: int64

----------
['first', 'second', None]
----------

              A  B
first second
bar   one     1  2
      two     3  4
baz   Two     7  8
      one     5  6

['first', 'second']

second   Two  one  two
first
bar   A  NaN  1.0  3.0
      B  NaN  2.0  4.0
baz   A  7.0  5.0  NaN
      B  8.0  6.0  NaN

              A  B
first second
bar   one     1  2
      two     3  4
baz   Two     7  8
      one     5  6

# ddd